### ISSUE TITLE
Primary key name is different from "id"

### ISSUE THREAD

**Issue by humeniuc** [hastenax/yii-cmanymanyactiverecord#1]
I have an model which primaryKey's name is different from Id. so the verifyManyManyRelation method throws an exception

The Property "ModelName.id" is not defined

>   protected function verifyManyManyRelation($relation) {
>        //check if relation correct
>        if ($this->id < 1)
>                    throw new CException($relation->name.' relation error, save model first');

Also, in "setRelationRecords" I saw the following code. I presume that it wil also fail:

$sql = "delete from {$table} WHERE $this_key = '{$this->id}'";

**Comment by hastenax** [comment]
Thanks for feedback! Can you test the fix?
